def detect(path: str) -> str: ...
def sparse_to_raw(input: str, output: str) -> None: ...
def sparse_chunks_to_raw(inputs: list[str], output: str) -> None: ...
def is_sparse(path: str) -> bool: ...
def nb0(input: str, output_dir: str) -> list[str]: ...
def pac(input: str, output_dir: str) -> list[str]: ...
def mtk_sign(input: str, output_dir: str) -> list[str]: ...
def ozip(input: str, output_dir: str) -> list[str]: ...
def sin(input: str, output_dir: str) -> list[str]: ...
def amlogic(input: str, output_dir: str) -> list[str]: ...
def rockchip(input: str, output_dir: str) -> list[str]: ...
def qfil(input: str, output_dir: str) -> list[str]: ...
def zte(input: str, output_dir: str) -> list[str]: ...
def kddi(input: str, output_dir: str) -> list[str]: ...
